- hosts: 100.100.176.126
  become: true
  gather_facts: no
  vars:
    exist_path: "/u02/filesystem/migration/"
  tasks:
    - name: get the package directory
      set_fact:
        exist_path: "{{ exist_path + Package_file }}"

    - name: print the value
      debug:
        var: exist_path

    - name: fetch package file from dev to ansible
      fetch: src={{ exist_path }} dest=/scratch/jenkins_home

- hosts: 100.100.181.24
  become: true
  vars:
    exist_path: "/u02/filesystem/migration/"
    dest_path: "/u02/filesystem/migration/"
  tasks:
    - name: get the package file directory
      set_fact:
        exist_path: "{{ exist_path + Package_file }}"

    - name: Migrate package file from ansible to dev
      copy: src=/scratch/jenkins_home/100.100.176.126/{{ exist_path }} dest={{ dest_path}}
    
    - name: file permission change
      shell: |
        chown oracle:oinstall {{ exist_path }}
        chmod 775 {{ exist_path }}

- hosts: localhost
  #become: true
  tasks:
    - name: delete the temp dir/file
      command: rm -rf 100.100.176.126 chdir=/scratch/jenkins_home
